### PR TITLE
 Add more responsiveness to cards and faq's

### PR DESCRIPTION
**Pull request by imabhi786**

### CODE REVIEW

**Comment by littlestar642** [comment]
@imabhi786 Can you please show me a deployment of your branch. You can use bitballoon to host your html.

**Comment by imabhi786** [comment]
@littlestar642 see the link hacksvnit.bitballoon.com

**Comment by imabhi786** [comment]
@littlestar642 see the link [](hacksvnit.bitballoon.com)

**Comment by imabhi786** [comment]
@littlestar642 click [here](hacksvnit.bitballoon.com)

**Pull request merged**
